---
title: "BSC6926-B53B Spring 2025"
format: html
---

#### BSC6926-B53B: Using a multivariate tool to assess population and community dynamics

This is the course website for the R workshop *Using a multivariate tool to assess population and community dynamics*. This website will have the Quarto markdown lessons for each workshop. Find the course schedule and Syllabus [here](sylb.html). This course will be based in R and information about downloading R and Rstudio can be found [here](comp.html).

### Class Resources

-   [Zoom link](https://fiu.zoom.us/j/94001884298?pwd=b25VZTh6eHFlOVdjRDhrbUV6OTBVZz09)
-   [Github repository](https://github.com/SeascapeEcologyLab-workshops/BSC6926-B53B_Spring2025)

### R Resources

-   R for Data Science by Hadley Wickham and Garret Grolemund -- An introduction to programming with R: <https://r4ds.hadley.nz/>\
-   Quick-R by datacamp: Quick overview on R programming and statistical approaches. There are more tutorials, but you will be required to register\
-   RStudio Cloud Training Exercises: <https://rstudio.cloud/learn/primers>\
-   Rstudio: learn R <https://education.rstudio.com/learn/beginner/>
